sonar.projectKey=elizondohdz_eCommerceSiteTesting
sonar.organization=elizondohdz

sonar.sources=backend/app,frontend/src

sonar.tests=backend/tests,frontend/cypress

sonar.php.coverage.reportPaths=backend/coverage.xml

sonar.sourceEncoding=UTF-8
