name: CI Pipeline

on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main, develop]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Prepare Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Create SQLite database
        working-directory: backend
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations and seeders
        run: php artisan migrate --seed --env=testing

      - name: Run Unit and Feature tests
        run: php artisan test --coverage-clover coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: laravel-coverage
          path: backend/coverage.xml

  frontend-e2e:
    runs-on: ubuntu-latest
    needs: backend-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Backend setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, sqlite, pdo_sqlite

      - name: Install backend dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist

      - name: Prepare backend environment
        working-directory: backend
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Run migrations and seeders
        working-directory: backend
        run: php artisan migrate --seed --env=testing

      - name: Start Laravel server
        working-directory: backend
        run: php artisan serve --host=127.0.0.1 --port=8000 &

      # Frontend + Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          working-directory: frontend
          start: npm run dev
          wait-on: http://localhost:5173

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots

      - name: Upload Mochawesome reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: frontend/cypress/reports

  postman-api-testing:
    runs-on: ubuntu-latest
    needs: backend-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Backend setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, sqlite, pdo_sqlite

      - name: Install backend dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist

      - name: Prepare backend environment
        working-directory: backend
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Run migrations and seeders
        working-directory: backend
        run: php artisan migrate --seed --env=testing

      - name: Start Laravel server
        working-directory: backend
        run: php artisan serve --host=127.0.0.1 --port=8000 &

      # Install Newman and Run postman collection tests
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run API Contract Tests
        working-directory: postman
        run: |
          newman run collections/ecommerce-api.json \
          -e environments/local.postman_environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export reports/report.html

      - name: Upload Newman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: postman/reports

  sonarqube:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-e2e]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
